OPENAI_DATA {
  id: 'resp_010a59ee7b48203800699c5ee20af481929d2721ad78413f18',
  object: 'response',
  created_at: 1771855586,
  status: 'completed',
  background: false,
  billing: { payer: 'developer' },
  completed_at: 1771855587,
  error: null,
  frequency_penalty: 0,
  incomplete_details: null,
  instructions: null,
  max_output_tokens: null,
  max_tool_calls: null,
  model: 'gpt-4o-mini-2024-07-18',
  output: [
    {
      id: 'msg_010a59ee7b48203800699c5ee2fba88192ad952b8edbc98809',
      type: 'message',
      status: 'completed',
      content: [Array],
      role: 'assistant'
    }
  ],
  parallel_tool_calls: true,
  presence_penalty: 0,
  previous_response_id: null,
  prompt_cache_key: null,
  prompt_cache_retention: null,
  reasoning: { effort: null, summary: null },
  safety_identifier: null,
  service_tier: 'default',
  store: true,
  temperature: 1,
  text: { format: { type: 'text' }, verbosity: 'medium' },
  tool_choice: 'auto',
  tools: [],
  top_logprobs: 0,
  top_p: 1,
  truncation: 'disabled',
  usage: {
    input_tokens: 28,
    input_tokens_details: { cached_tokens: 0 },
    output_tokens: 10,
    output_tokens_details: { reasoning_tokens: 0 },
    total_tokens: 38
  },
  user: null,
  metadata: {}

